.github/ISSUE_TEMPLATE/bug_report.md

Added the following in the bug issue template's description:
Related User Story:
(Delete this) Specify the issue number (eg: #1).
Other Related Issue:
(Delete this) If applicable, specify the issue number (eg: #1, #2, ...).

refactor: added additional description in bug issue template

---

README.md

Added my student id and github username.

docs(issue-25): update README

---

ERP/resources/views/components/navbar.blade.php
ERP/resources/views/jobs.blade.php
ERP/routes/web.php

when logged in, on the nav bar, click on jobs table.

feat(issue-60): created a ui for the jobs table

---

ERP/resources/views/User/create-user.blade.php
ERP/resources/views/User/user-management.blade.php

Closes #63 
- Converted Bootstrap 5 CSS to bootstrap 4.6.x

bugfix(issue-63): fix bootstrap version change

---

.idea/php-test-framework.xml
ERP/app/Http/Controllers/BikeController.php
ERP/app/Http/Controllers/MaterialController.php
ERP/app/Http/Controllers/PartController.php
ERP/resources/views/components/navbar.blade.php
ERP/resources/views/inventory.blade.php
ERP/routes/web.php

Information from DB tables is now being pulled into the Inventory page. New rows can be added through this page (Modified the form for bicycles to include dropdown selection). Similarly, rows can be edited or deleted. Status of the stock is clearly indicated through color coding when the stock of a particular item is low (less than 10).

task(issue-44): display notifications when bikes, parts, or materials are low

---

ERP/resources/views/inventory.blade.php

Removed extra double quotes symbol causing edit button to break.

bug(issue-69): fixed broken edit parts button

---

ERP/app/Http/Controllers/JobController.php
ERP/resources/views/jobs.blade.php
ERP/routes/web.php

In the "Job" page:
- Changed the "Edit" status button to "Toggle Status"
- When the "Toggle Status" button is clicked, it will toggle value (ie. If the status was "Queued", it will become "Complete", if it is "Complete", it will become "Queued")

task(issue-57): add backend to update bicycle completion status

---

ERP/database/factories/UserFactory.php
ERP/tests/Feature/InventoryTest.php

Added tests for inventory page under the file InventoryTest.php

task(issue-76): added new tests for inventory

---

ERP/app/Http/Controllers/BikeController.php

Removed extraneous space separating the word "inventory" in the redirect in BikeController.php.

bug(issue-83): fixed delete button for bikes

---

ERP/app/Http/Controllers/BikeController.php
ERP/app/Http/Controllers/MaterialController.php
ERP/app/Http/Controllers/PartController.php

Added descriptive comments for the controllers used in the inventory page.

task(issue-84): added comments for inventory controllers 

---

ERP/database/seeders/DatabaseSeeder.php
ERP/database/seeders/DefaultOrderSeeder.php
ERP/database/seeders/MasterUserSeeder.php

When doing php artisan db:seed, some default orders will now be added. 
Furthermore, added some default profiles for different user types.

task(issue-129): added some default orders to orders table and some default users to users table

---

ERP/tests/Unit/ShippingTest.php

Added tests to test the view and the toggle button.

task(issue-132): add unit tests for shipping

---

README.md

Updated the readme file
Closes #133

task(issue 133): updated readme file

---

README.md

Task/issue 133/update readme/kelvin

---

ERP/app/Http/Kernel.php
ERP/app/Http/Middleware/ManufacturerAccessOnly.php
ERP/routes/web.php
ERP/tests/Unit/ManufacturingTest.php

Add test files for machine status tests.

task(issue-146): add unit tests for machine status

---

ERP/resources/views/components/navbar.blade.php

The "Jobs" and "Assembly" pages are now only accessible via a manufacturer worker.

bug(issue-149): restrict "Jobs" and "Assembly" to Manufacturer Worker #149

---

ERP/tests/Unit/AccountantTest.php

**Description of the test:**
- Includes 1 test that checks if the Sales page can be rendered

testing(issue-147): add test to accountant 

---

ERP/composer.json
ERP/composer.lock
ERP/phpstan.neon

This PR addresses issue #155
- [Larastan](https://github.com/nunomaduro/larastan) static analysis tool was added to our project
- Added a base configuration file to project ROOT, so that the analysis can be run
- Configuration file is called `phpstan.neon`
- This configuration file is written in NEON, which is similar to YAML
- Currently, the tool found **69** errors
- Below is a detailed report of the errors found by the static analysis tool
```
Note: Using configuration file /home/pira/SOEN-390-Team5/ERP/phpstan.neon.
44/44 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%
------ --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Line …
```

task(issue-155): added static analysis tool to project

---

ERP/tests/Unit/InventoryTest.php

Fixed delete materials, as well as added tests for edit parts and materials.

task(issue-154): added test for parts and materials

---

ERP/app/Http/Controllers/SaleController.php
ERP/resources/views/Logging/log-page.blade.php
ERP/resources/views/accountant.blade.php
ERP/resources/views/layouts/master.blade.php
ERP/routes/web.php

Created a button that exports info of the sales tab
Note: I also changed the javascript function's name 'exportLogs' to 'exportTasks' in master.blade.php since the function is not only used by logs. The export button for the Logs still works (I changed exportLogs to exportTasks  in log-page.blade as well). @pirasunt

task(issue-136): Add export button for Sales

---

ERP/app/Charts/SaleChart.php
ERP/app/Providers/AppServiceProvider.php
ERP/composer.json
ERP/composer.lock
ERP/config/charts.php
ERP/resources/views/accountant.blade.php
ERP/resources/views/layouts/master.blade.php

Added laravel chart plugin in composer 
*run composer install if your app crashes
Added a profit graph for the sales tab in the accountant view for all sales

feat:(issue-190): added graph to sales accountant view 

---

ERP/app/Http/Controllers/AccountantController.php
ERP/resources/views/accountant.blade.php

- Added orders details into accountant's view.
<hr>
**Orders table in accountant's view:**

task(issue-192): add orders to accountant view

---

ERP/app/Http/Kernel.php
ERP/app/Http/Middleware/AccountantAccessOnly.php
ERP/app/Http/Middleware/SalesAccessOnly.php
ERP/database/seeders/MasterUserSeeder.php
ERP/resources/views/components/navbar.blade.php
ERP/resources/views/components/user-type-dropdown.blade.php
ERP/resources/views/welcome.blade.php
ERP/routes/web.php

- Create accountant specific sections within the navbar and prevents other users to view accountant page but the accountants.
- Create sale specific sections within the navbar and prevents other users to view sales page but the sales worker.

feat(issue-203): create accountant and sales person middleware and seeders

---

ERP/app/Http/Controllers/JobController.php
ERP/app/Models/Job.php
ERP/database/migrations/2021_02_23_160206_create_jobs_table.php
ERP/database/seeders/DefaultJobSeeder.php
ERP/resources/views/create-job.blade.php
ERP/resources/views/jobs.blade.php
ERP/routes/web.php

- Added job quality to jobs (Not inspected, under inspection, passed inspection, failed inspection)
- Sets default job to not inspected, can be then edited.
- Organizes the status of the jobs.

feat(issue-200): edit jobs page for quality

---

ERP/app/Http/Controllers/JobController.php
ERP/resources/views/jobs.blade.php

Added a button on the jobs page which lists the parts of a specific bike.

feat(issue-201): display parts for specified bikes

---

ERP/app/Http/Controllers/JobController.php
ERP/resources/views/jobs.blade.php

**Features:**
- Separate the job tables into 4 for each different status
- In progress
- Queued
- Completed
- Issue
- You can now view parts associated with a job
** This is a PR in attempt to fix PR#208 (@mandocino please review if it is according to what you want)

feat(issue-200): seperate jobs into categories and allow viewing of parts associated with a job

---

ERP/app/Http/Controllers/BikeController.php
ERP/app/Http/Controllers/PartController.php
ERP/resources/views/inventory.blade.php

Product managers and Inventory users can now properly edit a bike and part.
- Added category field for editing part
- Added part specification for editing bike.

bug(issue-221): fixed edit bike and edit part buttons in inventory

---

ERP/app/Http/Kernel.php
ERP/app/Http/Middleware/AssemblyAccessOnly.php
ERP/routes/web.php
ERP/tests/Unit/AssemblyTest.php
ERP/tests/Unit/InventoryTest.php

Added 1 unit test for Assembly: 
and fixed unit tests for Inventory:

feat(issue-206): added unit tests for assembly and inventory

---

ERP/tests/Unit/JobTest.php
ERP/tests/Unit/SalesWorkerTest.php

Created test cases for accountant and sales page access.

task(issue-206): add test cases

---

.idea/workspace.xml
ERP/config/session.php

- Set the Session timeout to 30 minutes.
- User is logged out after 30 min of inactivity

feat(issue-105): logout after inactivity + encrypt session

---

ERP/app/Http/Controllers/AccountantController.php

added logging to export order functions

Task(issue 209): added logs to order exports

---

ERP/tests/Unit/JobTest.php
ERP/tests/Unit/LogTest.php
ERP/tests/Unit/ShippingTest.php

feat(issue-206): Fixed unit tests for Jobs, Shipping, and Logs

---

ERP/resources/views/Logging/log-page.blade.php
ERP/resources/views/User/login.blade.php
ERP/resources/views/User/user-management.blade.php
ERP/resources/views/accountant.blade.php
ERP/resources/views/assembly.blade.php
ERP/resources/views/components/navbar.blade.php
ERP/resources/views/inventory.blade.php
ERP/resources/views/jobs.blade.php
ERP/resources/views/machine-status.blade.php
ERP/resources/views/sales.blade.php
ERP/resources/views/shipping.blade.php

- Made responsive tables
- improved UI for mobile

task(issue-223): made site more mobile-friendly

---

ERP/app/Http/Controllers/LogController.php
ERP/app/Http/Controllers/UserController.php

task: add comments

---

ERP/app/Http/Kernel.php
ERP/app/Http/Middleware/ManufacturerAndQualityAccessOnly.php
ERP/database/seeders/MasterUserSeeder.php
ERP/resources/views/components/navbar.blade.php
ERP/resources/views/components/user-type-dropdown.blade.php
ERP/resources/views/welcome.blade.php
ERP/routes/web.php

- Added new user type for Quality Control
- Has access to Jobs and Machine Status page since he will need to turn off machines if quality is poor

task(issue-227): create new quality control user type

---

ERP/tests/Unit/AccountantTest.php
ERP/tests/Unit/InventoryTest.php
ERP/tests/Unit/SalesWorkerTest.php

Added unit tests for accountants and sales.

feat(issue-206): added unit tests for Accountants and Sales
